### ISSUE TITLE
Coreference chain in xml files

### ISSUE THREAD

**Issue by yujianll** [cltl/ecbPlus#1]
Hi,

Thanks for sharing this great dataset!

I have a question about the tag in xml files. For example, in 1_1ecb.xml, for this relation:
```
<CROSS_DOC_COREF r_id="37538" note="ACT16235311629112331" >
  <source m_id="41" />
  <target m_id="43" />
</CROSS_DOC_COREF>
```
Is the source m_id="41" in this document? But what is the document id for the target mention? i.e., where can I find target m_id="43"?

Also, what does this tag mean:
```<ACTION_OCCURRENCE m_id="50" RELATED_TO="" TAG_DESCRIPTOR="t1b_checking_in_promises" instance_id="ACT16236402809085484" />?```

**Comment by piekvossen** [comment]
The identifiers represent event instances. You can search for them across the data as they are unique. Within the same folder ids represent the seminal events.

Piek

Sent from my iPad

On 3 Feb 2022, at 21:35, Yujian Liu ***@***.***> wrote:

﻿

Hi,

Thanks for sharing this great dataset!
I have a question about the tag in xml files. For example, in 1_1ecb.xml, what does this tag mean:
<ACTION_OCCURRENCE m_id="50" RELATED_TO="" TAG_DESCRIPTOR="t1b_checking_in_promises" instance_id="ACT16236402809085484" />? Does this mean m_id 50 in document ACT16236402809085484?

**Comment by yujianll** [comment]
Thanks!

**Comment by piekvossen** [comment]
I added some explanation to the readme file. I hope this helps.

Piek


On 3 Feb 2022, at 21:35, Yujian Liu ***@***.******@***.***>> wrote:



Hi,

Thanks for sharing this great dataset!
I have a question about the tag in xml files. For example, in 1_1ecb.xml, what does this tag mean:
<ACTION_OCCURRENCE m_id="50" RELATED_TO="" TAG_DESCRIPTOR="t1b_checking_in_promises" instance_id="ACT16236402809085484" />? Does this mean m_id 50 in document ACT16236402809085484?
